### PR TITLE
A buyer should be able to checkout

### PR DESCRIPTION
**Pull request by Jadowacu1**

### CODE REVIEW

**Review by SaddockAime — APPROVED** [review]

**Review by Aime-Patrick — CHANGES_REQUESTED** [review]
image
`**Why did you change the design? What will happen if 100 products are ordered? Are you going to display all of them like that? **`

**Review by Aime-Patrick — COMMENTED** [review]
Why does each cart have a `checkout` button? What is the purpose of that checkbox?

**Comment by Jadowacu1** [comment]
> image `**Why did you change the design? What will happen if 100 products are ordered? Are you going to display all of them like that? **`

**Review by ndahimana154 — APPROVED** [review]

**Comment by Jadowacu1** [comment]
> Why does each cart have a `checkout` button? What is the purpose of that checkbox?

This button is there to make checkout of single cart and about the checkbox it is going to be used for updating cart and deleting cart

**Comment by Jadowacu1** [comment]
> image `**Why did you change the design? What will happen if 100 products are ordered? Are you going to display all of them like that? **`

We decide to go with this design on the prevoious standup we did

**Review by Aime-Patrick — APPROVED** [review]

**Review by Aime-Patrick — COMMENTED** [review]
image
`I am not satisfied with this`

**Pull request merged**
