### PR TITLE
Users should be presented with a reset password link

### PR DESCRIPTION
**Pull request by Jadowacu1**

### CODE REVIEW

**Comment by Jadowacu1** [comment]
p2

**Comment by Jadowacu1** [comment]
p4

**Review by Aime-Patrick — COMMENTED** [review]
on cart icon put $0 not $100 and image of our site is invisible also put your image in description of PR not in commet

**Review by ndahimana154 — APPROVED** [review]

**Review by Aime-Patrick — APPROVED** [review]

**Review by hbapte — APPROVED** [review]

**Review by SaddockAime — APPROVED** [review]

**Review by Aime-Patrick — COMMENTED** [review]
Change your main background to white gray variable name is `$container-color` look in colors

**Pull request merged**
